name: gcp_music
version: "1.0.0"
config-version: 2

profile: gcp_music

model-paths: ["models"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  gcp_music:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    mart:
      +materialized: table
